<a href="https://colab.research.google.com/github/divyyanshii/handwritten_digit/blob/main/kaggle2repeat.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import sklearn.ensemble
import sklearn.manifold
import sklearn.decomposition
import sklearn.metrics
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [ ]:
data=pd.read_csv('/content/train.csv')
test=pd.read_csv('/content/test.csv')

np.sum(data.iloc[:,1:94] > 40)


feat_1      0
feat_2      0
feat_3      0
feat_4      9
feat_5      0
           ..
feat_89     3
feat_90    43
feat_91     0
feat_92     0
feat_93     1
Length: 93, dtype: int64

In [ ]:
X=np.asarray(data.iloc[:,1:-1].dropna(),dtype=np.float32)
print (X.shape)
Y=np.asarray(data.iloc[:,-1])
print (Y, Y.shape, len(np.unique(Y)))

(10000, 93)
[6 6 2 ... 6 3 3] (10000,) 9


In [ ]:
from sklearn.preprocessing import StandardScaler
X_stan = StandardScaler().fit_transform(X)
X_stan

array([[-0.26990068, -0.22786725,  3.9617624 , ..., -0.12505652,
        -0.38217062, -0.11774571],
       [-0.26990068, -0.22786725,  5.0311604 , ..., -0.12505652,
         0.6097075 , -0.11774571],
       [ 1.1446731 , -0.22786725, -0.3158288 , ..., -0.12505652,
        -0.38217062, -0.11774571],
       ...,
       [-0.26990068, -0.22786725,  4.3182282 , ..., -0.12505652,
        -0.38217062, -0.11774571],
       [ 1.1446731 , -0.22786725, -0.3158288 , ..., -0.12505652,
        -0.38217062, -0.11774571],
       [-0.26990068, -0.22786725, -0.3158288 , ..., -0.12505652,
        -0.38217062, -0.11774571]], dtype=float32)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_stan, Y, test_size=0.2, shuffle = False)
X_train.shape

(8000, 93)

In [ ]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(X_train)
model_pca_trans = pca.fit_transform(X_train)

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV

lr = LogisticRegression(n_jobs = -1)

# Set of parameters we want to try for out Model
parameters = { 'C' : np.power(10., np.arange(-4,4,1,dtype=int))}

#Running the Model with above chosen parameter
grid_search = GridSearchCV(estimator = lr, param_grid = parameters , scoring = 'accuracy', cv = 3, n_jobs = -1 , verbose = 2)
grid_scores = grid_search.fit(X_train , y_train)

print(grid_search.best_params_, '\n')
print(grid_search.best_score_, '\n')
print(grid_search.best_estimator_, '\n')

Fitting 3 folds for each of 8 candidates, totalling 24 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  24 out of  24 | elapsed:   11.8s finished


{'C': 1.0} 

0.7489998202587768 

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=-1, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) 



In [ ]:
from sklearn import metrics

print('LogisticRegression')
print('accuracy', metrics.accuracy_score(y_test, grid_search.predict(X_test)))

LogisticRegression
accuracy 0.7615


In [ ]:
rf= RandomForestClassifier(n_estimators=200)

# Set of parameters we want to try for out Model
parameters_rf = {'max_depth': np.arange(2,48,2,dtype=int)}

#Running the Model with above chosen parameter
grid_search_rf = GridSearchCV(estimator = rf, param_grid = parameters_rf , scoring = 'accuracy', cv = 3, n_jobs = -1 , verbose = 2)
grid_scores = grid_search_rf.fit(X_train , y_train)

print(grid_search_rf.best_params_, '\n')
print(grid_search_rf.best_score_, '\n')
print(grid_search_rf.best_estimator_, '\n')
print('accuracy', metrics.accuracy_score(y_test, grid_search_rf.predict(X_test)))

Fitting 3 folds for each of 23 candidates, totalling 69 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  37 tasks      | elapsed:   49.4s
[Parallel(n_jobs=-1)]: Done  69 out of  69 | elapsed:  1.9min finished


{'max_depth': 34} 

0.7681249614990925 

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=34, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False) 

accuracy 0.78


In [ ]:
test_=np.asarray(test.iloc[:,1:].dropna(),dtype=np.float32)
#print(X_test.shape)
rf = RandomForestClassifier(n_estimators=200)
rf.fit(X,Y)
pred = rf.predict(test_)
pred

array([5, 2, 8, ..., 6, 3, 6])

In [ ]:
c1 = np.zeros(test_.shape[0],dtype=int)
c1[pred==1] = 1
c2 = np.zeros(test_.shape[0],dtype=int)
c2[pred==2] = 1
c3 = np.zeros(test_.shape[0],dtype=int)
c3[pred==3] = 1
c4 = np.zeros(test_.shape[0],dtype=int)
c4[pred==4] = 1
c5 = np.zeros(test_.shape[0],dtype=int)
c5[pred==5] = 1
c6 = np.zeros(test_.shape[0],dtype=int)
c6[pred==6] = 1
c7 = np.zeros(test_.shape[0],dtype=int)
c7[pred==7] = 1
c8 = np.zeros(test_.shape[0],dtype=int)
c8[pred==8] = 1
c9 = np.zeros(test_.shape[0],dtype=int)
c9[pred==9] = 1
o = test[['ID']]
#c1.shape
o['Class_1'] = pd.Series(c1)
o['Class_2'] = pd.Series(c2)
o['Class_3'] = pd.Series(c3)
o['Class_4'] = pd.Series(c4)
o['Class_5'] = pd.Series(c5)
o['Class_6'] = pd.Series(c6)
o['Class_7'] = pd.Series(c7)
o['Class_8'] = pd.Series(c8)
o['Class_9'] = pd.Series(c9)
o.head()
o.to_csv("submit2.csv", index=False)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:21: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:23: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stab